Algoritmo "OPERADORES RELACIONAIS"
// Disciplina   : [Lógica computacional]
//  
// Descrição   : OPERADORES RELACIONAIS
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2023
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVAL("= Igualdade")
ESCREVAL("> Maior")
ESCREVAL("< Menor")
ESCREVAL(">= Maior e igual")
ESCREVAL("<= Menor e igual")
ESCREVAL("<> Diferenca")

Fimalgoritmo